feat: support --list-hosts tools command
trzsz/trzsz-ssh pull request #134
Opened 2024-08-12 14:13 UTC by qcu266

support list all tssh hosts.

in my case, I want to use wezterm to integrate tssh for ssh session management.

```lua
-- tssh.lua
local wezterm = require 'wezterm'

local M = {}

local function host_list()
    local hosts = {}
    local success, stdout, stderr = wezterm.run_child_process {
        'tssh',
        '--list-hosts',
    }
    hosts = wezterm.json_parse(stdout)

    return hosts
end

local function make_tssh_label_func(host)
    return wezterm.format {
        { Foreground = { AnsiColor = 'Green' } },
        { Text = "groups:" .. host["GroupLabels"] },
    }
end

local function make_tssh_fixup_func(alias)
    return function(cmd)
        local wrapped = {
            "tssh",
            alias,
        }
        cmd.args = wrapped
        -- wezterm.log_error(cmd)

        return cmd
    end
end

function M.compute_exec_domains()
    local exec_domains = {}
    for _, host in pairs(host_list()) do
        local alias = host["Alias"]
        local fixup = make_tssh_fixup_func(alias)
        local label_func = make_tssh_label_func(host)
        table.insert(
            exec_domains,
            wezterm.exec_domain(
                'tssh:' .. alias,
                fixup,
                label_func
            )
        )
    end
    return exec_domains
end

return M
```

```lua
-- wezterm.lua
local wezterm = require 'wezterm'
local tssh = require('tssh')

local config = {}
if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.exec_domains = tssh.compute_exec_domains()
```

2024-08-12 23:53 UTC, lonnywong commented
@qcu266 Thanks for the PR.

Can you also write a simple user guide for it? Consider putting it on the [wiki](https://github.com/trzsz/trzsz-ssh/wiki). It can be Chinese or English.

It is best to describe the advantages of the integration, or record a screen to show it.

2024-08-13 12:02 UTC, lonnywong commented on tssh/tools.go
> +	tea "github.com/charmbracelet/bubbletea"
Is this necessary? Or is it a lint warning?

2024-08-13 12:05 UTC, lonnywong commented on tssh/args.go
> +	ListHosts      bool        `arg:"--list-hosts" help:"[tools] list all hosts in configuration"`
Please move to the position after `--enc-secret`.

2024-08-13 12:08 UTC, lonnywong commented on tssh/tools.go
> +			panic(err)
It would be better to use `warning("json marshal indent failed: %v", err)` and `return 1, true`.

2024-08-13 12:09 UTC, lonnywong commented on tssh/tools.go
> +			hostsJson = strings.ReplaceAll(hostsJson, "\n", "\r\n")
Is the replacement with `\r\n` necessary?

2024-08-13 12:17 UTC, lonnywong commented on tssh/tools.go
> +		hosts := getAllHosts()
Field `Selected` should not be exported.

```diff
@@ -64,7 +64,7 @@ type sshHost struct {
        ProxyJump     string
        RemoteCommand string
        GroupLabels   string
-       Selected      bool
+       Selected      bool `json:"-"`
 }
```

2024-08-14 03:26 UTC, qcu266 commented on tssh/tools.go
> +	tea "github.com/charmbracelet/bubbletea"
vscode auto format when save

2024-08-14 03:35 UTC, qcu266 commented on tssh/tools.go
> +			hostsJson = strings.ReplaceAll(hostsJson, "\n", "\r\n")
Yes, otherwise the output on the windows terminal will be ugly

2024-08-14 03:51 UTC, qcu266 commented on tssh/tools.go
> +			panic(err)
fix.

To ensure that the output is always a valid JSON, when hosts is nil, set it to an empty slice.

```suggestion
		if hosts == nil {
			hosts = []*sshHost{}
		}
```

2024-08-14 09:11 UTC, lonnywong requested changes

2024-08-14 09:11 UTC, lonnywong commented on tssh/tools.go
> +	case args.ListHosts:
Please make a new function `execListHosts` in `tools_list_hosts.go`. You can refer to `tools_enc_secret.go`.

2024-08-14 10:19 UTC, merged